# Generated by Django 5.1.7 on 2025-03-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants_restaurant',
        ),
    ]
