# Generated by Django 5.1.7 on 2025-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
